# Generated by Django 3.1.12 on 2025-05-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('ingresosTotales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gastosTotales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ingresosAcumulados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gastosAcumulados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldoAcumulado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('egresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoResultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('costos_ventas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('utilidad_bruta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gastos_operativos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('utilidad_operativa', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('utilidad_neta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_impuesto', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('metodoPago', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ingresos_proyectados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gastos_proyectados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_proyectado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReporteFinanciero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gastos_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
